version: '3.0'
services:
  streetmerchant:
    image: docker.io/fabianr/ps5bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetmerchant
    env_file:
      - dotenv
